### ISSUE TITLE
Do not define internal libstdc++ macros

### ISSUE THREAD

**Issue by jwakely** [fsaintjacques/disruptor--#11]
`test/Makefile.am` and `perf/Makefile.am` both add `-D_GLIBCXX_USE_SCHED_YIELD -D_GLIBCXX_USE_NANOSLEEP` to compilation flags.  Those macros are internal libstdc++ implementation details and **not** for users to define or undefine.

If you want those features to be defined then you should configure GCC with `--enable-libstdcxx-time` instead of defining the macros

**Comment by fsaintjacques** [comment]
Good catch, these were mistakenly commited while I was testing on OSX.
