### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by krs43** [fsaintjacques/disruptor--#16]
I haven't tested anything yet - but is there any reason this wont work on Windows / VS.net 2012?

**Comment by fsaintjacques** [comment]
I'm not sure if VC 2012 supports C++0x extensions; it requires lambdas, atomic and threading support.

**Comment by krs43** [comment]
Just ported this to Windows in a very crude implementation. Most of the difficulty is in the time measurement -> had to convert to QueryPerformanceCounter. I'm seeing ~7 Million messages / second on a Nelhem i7 6 core + 6 hyperthreading in the 1P-1C performance test. This seems ~4 times slower than the java published numbers, but I'm sure it is not a fair comparison until I've dived in to the setup.

**Comment by fsaintjacques** [comment]
I believe that disabling hyperthread and pinning process to specific core is key.
