### ISSUE TITLE
How can I run it???

### ISSUE THREAD

**Issue by sunranlb** [fsaintjacques/disruptor--#21]
Hi, I put the program in my eclipse in ubuntu14.04, but I can't run it.
Even I make the Makefile in terminal, it doesn't work.
How can I run the test???
Thank you.

**Comment by fsaintjacques** [comment]
You need to bootstrap the directory with [autoreconf](https://www.gnu.org/savannah-checkouts/gnu/autoconf/manual/autoconf-2.69/html_node/autoreconf-Invocation.html). Then you can do the usual `./configure && make check`.
