### ISSUE TITLE
Is this still being maintained?

### ISSUE THREAD

**Issue by karopawil** [fsaintjacques/disruptor--#37]
Is this still being maintained? 

I started having a look at it and found two problems (reported issues). Separate instances of wait strategies so blocking wait strategy does not work. I can, in my tests, get it to work if I the sequence barrier has a reference to what the sequencer has.

NewBarrier does not compile. Can work around this by returning  a pointer.

Are there any plans to fix these? Or do I have to work with my own fork if I am interested in pursuing this project further?

Regards

**Comment by fsaintjacques** [comment]
I'll gladly merge PR if submitted.

**Comment by karopawil** [comment]
Have to get used to it (and varon-t) first to see if I can make a reasonable contribution.

Initial tests show excellent performance.

**Comment by fsaintjacques** [comment]
If this is for production software, I'd recommend varon-t instead :)

**Comment by karopawil** [comment]
I am just having a look it now as LMAX people had some pretty impressive benchmarks . Think something like this would be pretty useful. I would rather stick with C++11 and greater though. Think I can work with your stuff (and varon-t as a reference) to get it to do what I may need. A full blown java like disruptor is too much work.

**Comment by fsaintjacques** [comment]
Note that I initially ported this 1-1 from the Java implementation without deep knowledge of C++, it still shows.

There's also tradeoff I'd like to review, e.g. why is the ring-buffer backed array a template (thus compile time) parameter.

**Comment by karopawil** [comment]
I am not a C++ expert so I do not try to be fancy. I found your code (and varon-t) very helpful in understanding the concept as I was having a bit of a hard time last week to understand it from other sources (at least I have a better grip now). And with a couple of minor hacks to do some tests (1 prod thread, I consumer thread) I can get anywhere from 15/20 million sequences per second for the following dumb code (except for blocking strategy which is anywhere from 2/3 million. I hope I am doing it the right way) on my laptop. 

Ctl-C to stop :-)

#define RING_BUFFER_SIZE 1024
void consume()
{
  std::vector< disruptor::Sequence * > depseqs;
  std::unique_ptr< disruptor::SequenceBarrier< disruptor::SleepingStrategy<> > >
      barrier = s.NewBarrier(depseqs);

  int64_t next_seq = disruptor::kFirstSequenceValue;

  while (true)
  {
    int64_t available_seq = barrier->WaitFor(next_seq);

    seq1.set_sequence(available_seq);

    next_seq = available_seq + 1;
  }
}

void produce()
{
  for (int i = 0; i < 24000 * RING_BUFFER_SIZE; i++)
  {
    int64_t sequence = s.Claim();

    s.Publish(sequence);
  }
}

**Comment by fsaintjacques** [comment]
core pinning has a huge effect on said benchmarks, always use it.

**Comment by karopawil** [comment]
Thanks a lot. At least I have a good start now.

**Comment by karopawil** [comment]
Wonder if the performance of the blocking strategy could be improved? And CPU usage of the yield strategy decreased when nothing is happening? Something for later.
