### ISSUE TITLE
Use deleted functions to disallow copying

### ISSUE THREAD

**Issue by jwakely** [fsaintjacques/disruptor--#9]
As a C++11 project it would be better to use deleted copy constructors and copy assignment operators instead of the current DISALLOW_COPY_AND_ASSIGN macro.

Would a patch to change the macro (or just to declare deleted functions directly in the classes) be accepted?

**Comment by fsaintjacques** [comment]
I would gladly accept a patch.

**Comment by jwakely** [comment]
Created pull request https://github.com/fsaintjacques/disruptor--/pull/14
